package tools

import "github.com/panjie/mods/internal/prompts"

const ToolSelectionRules = prompts.ToolSelection

const PosixShellRunDescription = "Run a shell command via sh and return stdout+stderr. Commands already run with the configured workspace as their process cwd; do not prepend cd to that cwd. Output is returned directly; do not redirect to a file just to see results. Pipe commands together for filtering, counting, or text processing (e.g. find ... | wc -l)."

const WindowsShellRunDescription = "Run a PowerShell command via the available PowerShell host (pwsh.exe if present, otherwise powershell.exe) with -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command and return stdout+stderr. Commands already run with the configured workspace as their process cwd; do not prepend Set-Location, cd, or Push-Location to that cwd. Prefer powershell_run for Windows shell work; shell_run is a compatibility alias with the same PowerShell command syntax. Use native PowerShell cmdlets and pipelines such as Get-ChildItem, Select-String, Where-Object, Test-Path, Get-Content, and Measure-Object instead of POSIX-only utilities unless intentionally invoking an installed external program. " + prompts.PowerShellIntentGuidance + " Output is returned directly; do not use Out-File, Set-Content, shell redirection, or temporary .ps1 files just to see results."

const PowerShellRunDescription = "Run a PowerShell command directly via the available PowerShell host (pwsh.exe if present, otherwise powershell.exe) with -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command and return stdout+stderr. Pass only the PowerShell pipeline or script block; do not prefix with powershell, powershell.exe, pwsh, or -Command. Commands already run with the configured workspace as their process cwd; do not prepend Set-Location, cd, or Push-Location to that cwd. Use native PowerShell cmdlets and pipelines such as Get-ChildItem, Select-String, Where-Object, Test-Path, Get-Content, and Measure-Object instead of POSIX-only utilities unless intentionally invoking an installed external program. " + prompts.PowerShellIntentGuidance + " Output is returned directly; do not use Out-File, Set-Content, shell redirection, or temporary .ps1 files just to see results."

const ProcessRunDescription = "Run one executable directly with a literal argument vector and return a structured JSON result containing exit_code, separate stdout/stderr, duration, timeout state, and truncation metadata. Prefer this tool for tests, builds, git, package managers, and other single-program invocations because it avoids platform-specific shell quoting. Use shell_run or powershell_run only when shell syntax such as pipelines, redirection, variable expansion, globbing, or builtins is required. cwd defaults to the configured workspace."

const RuntimeInfoDescription = "Report the current OS, architecture, workspace, and the exact shell host selected by mods. Optionally resolve up to 20 bare command names on PATH without executing them. Use only when platform or command availability is relevant and not already known."
