package tools

import "github.com/panjie/mods/internal/prompts"

const ToolSelectionRules = prompts.ToolSelection

const PosixShellRunDescription = "Run a command that requires POSIX shell syntax and return stdout+stderr. Prefer process_run for one executable, including git, tests, builds, package managers, and installers. Use this tool for necessary pipelines, redirection, variable expansion, globbing, or shell builtins. Keep each call to one independently reviewable purpose. Commands already run with the configured workspace as their process cwd; do not prepend cd to that cwd. Output is returned directly; do not redirect to a file just to see results."

const WindowsShellRunDescription = "Run a PowerShell command via the available PowerShell host (pwsh.exe if present, otherwise powershell.exe) with -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command and return stdout+stderr. Commands already run with the configured workspace as their process cwd; do not prepend Set-Location, cd, or Push-Location to that cwd. Prefer powershell_run for Windows shell work; shell_run is a compatibility alias with the same PowerShell command syntax. Use native PowerShell cmdlets and pipelines such as Get-ChildItem, Select-String, Where-Object, Test-Path, Get-Content, and Measure-Object instead of POSIX-only utilities unless intentionally invoking an installed external program. " + prompts.PowerShellIntentGuidance + " Output is returned directly; do not use Out-File, Set-Content, shell redirection, or temporary .ps1 files just to see results."

const PowerShellRunDescription = "Run a PowerShell command directly via the available PowerShell host (pwsh.exe if present, otherwise powershell.exe) with -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command and return stdout+stderr. Pass only the PowerShell pipeline or script block; do not prefix with powershell, powershell.exe, pwsh, or -Command. Commands already run with the configured workspace as their process cwd; do not prepend Set-Location, cd, or Push-Location to that cwd. Use native PowerShell cmdlets and pipelines such as Get-ChildItem, Select-String, Where-Object, Test-Path, Get-Content, and Measure-Object instead of POSIX-only utilities unless intentionally invoking an installed external program. " + prompts.PowerShellIntentGuidance + " Output is returned directly; do not use Out-File, Set-Content, shell redirection, or temporary .ps1 files just to see results."

const ProcessRunDescription = "Run one native executable directly with a literal argument vector and return a structured JSON result containing exit_code, separate stdout/stderr, duration, timeout state, and truncation metadata. Prefer this tool for git, tests, builds, package managers, installers, and every other single-program invocation because it avoids platform-specific shell quoting. Set program to the intended executable itself: for example, use program=head for head -n 80 file; program=sh with args=[head,...] instead treats head as a script path. This includes interpreters with script or expression arguments (emacs --eval, python -c, node -e): pass each argument as one literal argv item even when it contains quotes, parentheses, spaces, or backslashes, and rely on the separate stdout/stderr fields instead of 2>&1. On POSIX systems, invoke sudo directly as the program when elevation is required; mods routes direct sudo through its secure askpass flow. Windows .bat and .cmd launchers are rejected because they cannot preserve literal argv; invoke them through powershell_run instead. Never invoke sh, cmd, powershell, or pwsh with -c, /C, or -Command through this tool; use shell_run or powershell_run for shell source. Keep discovery, mutation, and verification separate. cwd defaults to the configured workspace."

const RuntimeInfoDescription = "Report the current OS, architecture, workspace, and the exact shell host selected by mods. Optionally resolve up to 20 bare command names on PATH without executing them. Use only when platform or command availability is relevant and not already known."
